abbreviations = {
    # abilities
    "Str": "strength",
    "Dex": "dexterity",
    "Con": "constitution",
    "Int": "intelligence",
    "Wis": "wisdom",
    "Cha": "charisma",
    # classes
    "Alc": "alchemist",
    "Bbn": "barbarian",
    "Brd": "bard",
    "Cav": "cavalier",
    "Clr": "cleric",
    "Drd": "druid",
    "Ftr": "fighter",
    "Gun": "gunslinger",
    "Inq": "inquisitor",
    "Mag": "magus",
    "Mnk": "monk",
    "Ora": "oracle",
    "Pal": "paladin",
    "Rgr": "ranger",
    "Rog": "rogue",
    "Sor": "sorcerer",
    "Sum": "summoner",
    "Wit": "witch",
    "Wiz": "wizard"
}